version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    #working-directory: ~/blog-dapp-ethereum
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run:
          name: Installing client dependencies
          command: cd client/ && yarn
      - run:
          name: Building client
          command: cd client/ && CI=false yarn run build
      - run:
          name: Installing backend dependencies
          command: yarn
      - save_cache:
          paths:
            - client/node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
      #- run:
      # name: Running security tests
      #command: npm run test:security
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Running react tests
          command: yarn add react-scripts && SKIP_PREFLIGHT_CHECK=true yarn run test
      - run:
          name: Running truffle tests
          command: yarn run test

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
