version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    #working-directory: ~/blog-dapp-ethereum
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Running tests
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running truffle tests
          command: npm run test
      #- run:
       # name: Running security tests
        #command: npm run test:security

